// Link-preview cards — site/card-*.png
//
// Run: node scripts/build_cards.mjs   (from the repo root)
//
// WHY THESE EXIST. Every page already carried og:title, og:description and
// og:url, and every one declared twitter:card "summary" with no og:image — so
// anything anyone shared, anywhere, rendered as a small grey text card. That is
// fine for a page you land on and wrong for a publication: the work looked
// unpublished at precisely the moment somebody was passing it to someone else.
//
// ⚠️ SVG IS NOT AN OPTION. og:image is consumed by crawlers that do not run a
// renderer — X, Slack, LinkedIn, iMessage all reject SVG outright, and the
// failure is silent: no card, no warning, and the page looks like it has no
// image rather than like it has a broken one. It has to be a raster file.
//
// TYPE ONLY, ON PURPOSE. The three candidates were the chart cropped, the loop
// figure, and type. The chart is unmistakably ours and completely unreadable at
// the size a card is actually seen (a timeline card is ~300px wide, so the
// sheet's 13.5-unit copy lands at about one pixel). The loop figure reads, but
// it is already the pinned post's image and a card that repeats the post's
// picture says nothing twice. Type reads at every size and looks like a paper
// rather than a product, which is the whole posture. Decided 2026-08-21.
//
// ⚠️ THE TITLES ARE NOT KEPT HERE. Each card is drawn from the page's own
// og:title and og:description, read out of the file at build time. A hand-kept
// list of titles in a generator is exactly the copy nobody notices has gone
// stale, and this repo has been bitten by that before. Change a page's og:title
// and re-run; the card follows.
//
// ⚠️ NOT IN CI, DELIBERATELY. The generated PAGES are checked for staleness by
// the "generated pages are up to date" job, and these cards are not, because
// they are rasterised text: the same HTML renders to different bytes on Windows
// and on the CI runner, since the system font stacks resolve differently. A
// byte-comparison check would fail on every run and teach everyone to ignore it.
// These are regenerated by hand when a title changes, and committed.

import { readFile, readdir } from 'node:fs/promises';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const SITE = join(ROOT, 'site');

// Playwright belongs to the harness, not to the site, and this borrows it
// rather than adding a second copy: it is the only thing in the repo that can
// rasterise text, and the alternative is a dependency the site does not need.
// Run `npm install` in scripts/verify first.
const { chromium } = createRequire(join(HERE, 'verify', 'package.json'))('playwright');

const W = 1200, H = 630;             // the size every consumer crops toward

// The slot at the foot of the card, left of the domain. Papers carry their
// number because that is how they are cited; the rest carry what kind of page
// they are. Anything not listed falls back to the wordmark, which is never
// wrong, only quiet.
const LABEL = {
  index: 'The chart',
  patterns: 'Catalogue',
  contents: 'Contents',
  poster: 'Poster',
  why: 'About',
};

const meta = (html, prop) => {
  // Attribute order is not guaranteed, so match the property and then take the
  // content from the same tag rather than assuming the pair is adjacent.
  const tag = html.match(new RegExp('<meta[^>]*(?:property|name)="' + prop + '"[^>]*>', 'i'));
  if (!tag) return '';
  const c = tag[0].match(/content="([^"]*)"/i);
  return c ? c[1].replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>') : '';
};

const page = (title, standfirst, label) => `<!doctype html>
<html><head><meta charset="utf-8"><style>
  *{box-sizing:border-box;margin:0}
  html,body{width:${W}px;height:${H}px}
  body{background:#ffffff;color:#0d0f12;
    font-family:system-ui,-apple-system,"Segoe UI Variable Text","Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;
    padding:76px 80px;display:flex;flex-direction:column;justify-content:space-between}
  .mono{font-family:ui-monospace,"Cascadia Mono","SF Mono","Roboto Mono",Menlo,Consolas,monospace}
  .org{font-size:25px;letter-spacing:.34em;text-transform:uppercase;font-weight:500}
  h1{font-weight:600;letter-spacing:-.026em;line-height:1.04;font-size:96px}
  .sub{color:#5c626b;font-size:31px;line-height:1.4;margin-top:26px;max-width:900px}
  .foot{border-top:1px solid #e6e9ec;padding-top:22px;display:flex;
    justify-content:space-between;font-size:22px;letter-spacing:.16em;
    text-transform:uppercase;color:#5c626b}
</style></head><body>
  <p class="org mono">Organon Mind</p>
  <div><h1 id="t">${title}</h1><p class="sub" id="s">${standfirst}</p></div>
  <div class="foot mono"><span>${label}</span><span>organonmind.org</span></div>
</body></html>`;

const cards = [];
const browser = await chromium.launch();
const p = await browser.newPage({ viewport: { width: W, height: H }, deviceScaleFactor: 1 });

for (const file of (await readdir(SITE)).filter(f => f.endsWith('.html')).sort()) {
  const name = basename(file, '.html');
  const html = await readFile(join(SITE, file), 'utf8');
  const title = meta(html, 'og:title');
  if (!title) { console.log(`skip  ${name}  (no og:title)`); continue; }

  // A paper is cited by its number, so the number is the label. It is in the
  // filename and in <title>; the filename is the one that cannot be reworded.
  const label = LABEL[name] || (/^om-\d+$/.test(name) ? name.toUpperCase() : 'Organon Mind');
  const standfirst = meta(html, 'og:description');

  await p.setContent(page(title, standfirst, label), { waitUntil: 'load' });

  // Fit the title by stepping the size down rather than by guessing a
  // character count: the same string is a different width in every face this
  // stack can resolve to, and a title that overflows is silently cropped by
  // the screenshot with nothing to say it happened.
  const size = await p.evaluate(() => {
    const t = document.getElementById('t'), s = document.getElementById('s');
    const room = () => document.body.clientHeight - 152;   // less padding
    const used = () => document.querySelector('.org').offsetHeight +
                       t.parentElement.offsetHeight + document.querySelector('.foot').offsetHeight;
    if (!s.textContent.trim()) s.remove();
    let px = 96;
    while (px > 46 && used() > room() - 48) { px -= 2; t.style.fontSize = px + 'px'; }
    return px;
  });

  const out = `card-${name}.png`;
  await p.screenshot({ path: join(SITE, out), type: 'png' });
  cards.push({ name, out, size, title });
  console.log(`wrote site/${out}  ${String(size).padStart(3)}px  ${title}`);
}

await browser.close();
console.log(`\n${cards.length} cards`);
