// The contents page — organonmind.org/contents
//
// GENERATED by build_poster.mjs, from the same list the landing page uses.
//
// WHY THIS EXISTS. The front page became the chart, which is good at catching
// someone's attention and bad at being a table of contents: it is one tall
// drawing, and a reader who already knows they want OM-003 has to scroll past a
// poster to find it. This is the page the index used to be — the name and the
// list, nothing else — kept as a second front door rather than lost to the
// first. The switch between them sits on the wordmark line of both.
//
// ⚠️ IT IS DELIBERATELY THE PLAIN ONE. No chart, no drawing, no framing line.
// The temptation is to put a small version of the sheet at the top, and that
// would make it a worse copy of the page it exists to be an alternative to.
// What it gains from the chart existing is one row — the sheet, listed as a
// thing you can open and print — not a picture of it.
//
// ⚠️ THE LIST IS DERIVED. The papers come from the om-NNN.html files on disk,
// each supplying its own title from its masthead, and the builder throws if one
// exists that neither front door links. Both pages take the same array, so they
// cannot disagree about what has been published.

const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

export function contentsPage({ papers, nav, switchCss }) {
  const rows = papers.map(p => `      <li>
        <a href="${p.href}">
          <span class="label">${esc(p.label)}</span>
          <span class="title">${esc(p.title)}</span>
        </a>
      </li>`).join('\n');

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Contents — Organon Mind</title>
<meta name="description" content="Everything Organon Mind has published: the catalogue, the papers, and the sheet.">
<link rel="icon" href="/favicon.svg">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Organon Mind">
<meta property="og:title" content="Contents — Organon Mind">
<meta property="og:url" content="https://organonmind.org/contents">
<meta name="twitter:card" content="summary">
<style>
/* GENERATED — do not hand-edit. scripts/build_poster.mjs writes this file via
   scripts/contents.mjs. An edit here is lost at the next run, and worse, it is
   an edit to a copy. */
:root{
  --paper:#ffffff;--ink:#0d0f12;--muted:#5c626b;--faint:#9aa1a9;
  --rule:#e6e9ec;--rule2:#cdd2d8;--live:#1440c4;
  --sans:system-ui,-apple-system,"Segoe UI Variable Text","Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;
  --mono:ui-monospace,"Cascadia Mono","SF Mono","Roboto Mono",Menlo,Consolas,monospace;
}
*{box-sizing:border-box}
html{-webkit-text-size-adjust:100%}
body{margin:0;background:var(--paper);color:var(--ink);font-family:var(--sans);
  font-size:17px;line-height:1.6;-webkit-font-smoothing:antialiased}
main{max-width:46rem;margin:0 auto;padding:clamp(2.4rem,6vw,4.5rem) 1.5rem 7rem}
a{color:var(--live);text-underline-offset:2px;text-decoration-thickness:1px}

/* The wordmark as it always was: the same treatment as a publication masthead,
   scaled up, so the identity is one element used consistently rather than a
   logo. This page is the one that kept it. */
.org{font-family:var(--mono);font-weight:500;letter-spacing:.2em;
  font-size:clamp(1.05rem,2.6vw,1.5rem);text-transform:uppercase;color:var(--ink);margin:0}
.top{margin:0 0 2.4rem}
${switchCss}

.index{list-style:none;margin:0;padding:0;border-top:1px solid var(--rule2)}
.index li{border-bottom:1px solid var(--rule)}
.index a{display:block;padding:.95rem 0;text-decoration:none;color:inherit}
.index a:hover .title{text-decoration:underline;text-decoration-color:var(--live);
  text-underline-offset:3px}
.index .label{display:block;font-family:var(--mono);font-size:.66rem;
  letter-spacing:.14em;text-transform:uppercase;color:var(--faint);margin-bottom:.15rem}
.index .title{font-weight:600;letter-spacing:-.008em}
@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
</style>
</head>
<body>
<main>
  <div class="top"><p class="org">Organon Mind</p>${nav}</div>
  <ul class="index">
${rows}
  </ul>
</main>
</body>
</html>
`;
}
