#!/usr/bin/env node
// The catalogue's entry text — reproduced into site/patterns.html from the papers.
//
// WHY THIS EXISTS. Clicking a name in the chart lands on /patterns#<id>, and
// until now that showed the entry's intent, its position, its relations, and a
// link reading "The full entry, with its figure and its costs, is in OM-001 →".
// Two hops to read one pattern, and the page you land on looks like the entry
// without being it. James called it confusing and he is right: the chart's names
// are a promise, and the thing they open should be the thing they name.
//
// ⚠️ THIS DOES NOT REPEAL THE ONE-COPY RULE. It changes what enforces it. The
// rule was there because two hand-kept copies of a pattern drift, and the drift
// is invisible — nobody diffs a catalogue against a paper. There is still
// exactly one AUTHORED copy of every entry and it is in the paper. This script
// reproduces it, `build_poster.mjs` runs it, and CI's `generated` job rebuilds
// and fails if the tree moved. So the second copy cannot drift: it is not
// maintained, it is derived, and a paper edit that is not carried across turns
// a PR red. Hand-editing entry prose in patterns.html is now the mistake the
// rule was always about — see the marker comment this writes into the file.
//
// WHAT IS COPIED. The paper's `<div class="body">` for each `<section id=…>`,
// which is byte-for-byte what the explorer used to carry: measured against the
// pre-e1ec1f1 store blocks, 55 lines of 55 match, and the one that differs is
// `<p class="part">`, which `.prose .part{display:none}` hides anyway because
// the detail pane sets that line itself from the set's own group names.
//
// WHAT DOES THE RENDERING. Nothing here. `show()` in patterns.html has looked
// for `[data-pat="<id>"]` all along and taken the full-text branch when it found
// one — the machinery was never removed, only starved. It also lifts the entry's
// <figure> into the hero, and `.prose figure` is already display:none so the
// figure is not drawn twice. This script supplies the missing half.
//
//   node scripts/entries.mjs           # inject, and report what it wrote
//   node scripts/entries.mjs --check   # exit 1 if patterns.html is out of date
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { load } from './pattern_graph.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SITE = join(ROOT, 'site');
const TARGET = join(SITE, 'patterns.html');

export const BEGIN = '<!-- ENTRIES:BEGIN — generated by scripts/entries.mjs from the papers. -->';
export const END = '<!-- ENTRIES:END -->';

// The banner sits inside the generated region so it travels with it, and so
// anyone reading patterns.html hits it before they reach the prose.
const BANNER = [
  '<!-- ⚠️ DO NOT HAND-EDIT ANYTHING BETWEEN THESE MARKERS.',
  '     Every entry below is reproduced from its paper by scripts/entries.mjs,',
  '     which build_poster.mjs runs. An edit here is lost at the next build, and',
  '     worse, it is an edit to a copy: the paper stays wrong and the catalogue',
  '     silently disagrees with it. Fix the entry in om-00N.html and rebuild. -->',
].join('\n');

// Pull one entry's <div class="body"> inner HTML out of a paper. Depth-counted
// rather than regexed to a closing tag: the body contains nested divs, and a
// lazy match stops at the first </div> inside the figure, which yields a block
// that looks plausible and is missing two thirds of the entry.
export function entryBody(html, id) {
  const sec = html.indexOf(`<section id="${id}">`);
  if (sec < 0) return null;
  const open = html.indexOf('<div class="body">', sec);
  if (open < 0) return null;
  // Never cross into the next entry: a missing body would otherwise swallow the
  // rest of the paper rather than report itself.
  const nextSec = html.indexOf('<section id=', sec + 1);
  if (nextSec >= 0 && open > nextSec) return null;
  const start = open + '<div class="body">'.length;
  const re = /<\/?div\b/g;
  re.lastIndex = start;
  let depth = 1, m;
  while ((m = re.exec(html))) {
    depth += m[0][1] === '/' ? -1 : 1;
    if (depth === 0) return html.slice(start, m.index);
  }
  return null;
}

export async function storeBlocks() {
  const { langs, nodes } = await load();
  const byLang = new Map(langs.map(l => [l.id, l]));
  const papers = new Map();
  const blocks = [];
  const missing = [];

  for (const p of nodes) {
    const l = byLang.get(p.lang);
    if (!l) { missing.push(`${p.id}: no set "${p.lang}"`); continue; }
    const file = l.href.replace(/^\//, '') + '.html';
    if (!papers.has(file)) papers.set(file, await readFile(join(SITE, file), 'utf8'));
    let body = entryBody(papers.get(file), p.id);
    if (body === null) { missing.push(`${p.id}: no <section id="${p.id}"> in ${file}`); continue; }

    // ⚠️ A bare fragment means something different once the words move. The
    // papers cross-reference their own sections — `#slot-3`, `#open-questions`
    // — which do not exist here, so nine links silently pointed at nothing and
    // the harness caught every one. Rewritten to the paper they belong to.
    //
    // The tempting exception — leave `#gather` and friends alone so a prose
    // link keeps you inside the catalogue — would be BROKEN, not nicer: the
    // explorer routes on `popstate`, and a same-page fragment click fires
    // `hashchange`, which nothing here listens for. The URL would change and
    // the page would not. (No entry contains such a link today; this is the
    // note for whoever adds the first one and wonders why it does nothing.)
    body = body.replace(/href="#([^"]+)"/g, (_, frag) => `href="${l.href}#${frag}"`);
    // The provenance line is generated, never authored, so it cannot name the
    // wrong paper. The bar's own link says which paper you are in; this says
    // which document is answerable for these words.
    const from = `      <p class="reprinted">Reproduced from <a href="${l.href}#${p.id}">` +
                 `${l.doc} · the canonical entry</a>, which this catalogue does not replace.</p>`;
    blocks.push(`<div class="panel" data-pat="${p.id}">${body}${from}\n    </div>`);
  }

  // ⚠️ Throw rather than skip. A silently absent entry falls back to the old
  // "the full entry is in OM-001 →" stub, which is exactly the state this
  // change exists to end — and it would look like a page that simply had not
  // been updated yet rather than a build that failed.
  if (missing.length)
    throw new Error('entries.mjs cannot find these in the papers:\n  ' + missing.join('\n  '));

  return { html: blocks.join('\n'), count: blocks.length };
}

export async function render() {
  const src = await readFile(TARGET, 'utf8');
  const i = src.indexOf(BEGIN);
  const j = src.indexOf(END);
  if (i < 0 || j < 0 || j < i)
    throw new Error(`site/patterns.html is missing the ENTRIES markers — expected\n  ${BEGIN}\n  ${END}`);
  const { html, count } = await storeBlocks();
  // Match the file's own line endings. patterns.html is hand-authored and a
  // Windows checkout holds it as CRLF; writing LF into one region only would
  // leave the file mixed, which is a diff nobody meant to make.
  // ⚠️ Normalise to \n BEFORE re-applying, never split on '\n' alone: the papers
  // are CRLF too, so the extracted bodies already carry \r and a bare
  // split('\n').join('\r\n') writes \r\r\n through every reproduced line. It
  // looks fine in a browser and turns a pure insertion into a 1000-line diff.
  const nl = src.includes('\r\n') ? '\r\n' : '\n';
  const body = (BANNER + '\n' + html).replace(/\r\n?/g, '\n').replace(/\n/g, nl);
  const next = src.slice(0, i + BEGIN.length) + nl + body + nl + src.slice(j);
  return { next, src, count };
}

export async function inject() {
  const { next, src, count } = await render();
  if (next !== src) await writeFile(TARGET, next);
  return { count, changed: next !== src };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  const check = process.argv.includes('--check');
  const { next, src, count } = await render();
  if (check) {
    if (next !== src) {
      console.error('site/patterns.html is out of date — run: node scripts/build_poster.mjs');
      process.exit(1);
    }
    console.log(`site/patterns.html carries all ${count} entries, current.`);
  } else {
    if (next !== src) await writeFile(TARGET, next);
    console.log(`entries  ${count} reproduced into site/patterns.html` +
                (next === src ? ' (already current)' : ''));
  }
}
